apiVersion: v1        # Versión de la API de Kubernetes utilizada para definir un recurso de tipo "Service".
kind: Service         # Tipo de recurso: en este caso es un "Service" para exponer un conjunto de pods.

metadata:
  name: svc-dcsar-basic-landing-page  # Nombre del Service.
  namespace: dcsarapp                 # Namespace en el que se desplegará este Deployment.

spec:
  type: NodePort        # Tipo de Service: expone el servicio en un puerto del nodo (útil para acceso externo sin LoadBalancer).
  ports:
    - name: "30222"     # Nombre identificador del puerto (opcional, pero útil para referencias y debugging).
      nodePort: 30222   # Puerto específico del nodo por donde se podrá acceder externamente (debe estar entre 30000–32767).
      port: 30222       # Puerto del Service dentro del clúster (lo que otros pods usarán para conectarse).
      targetPort: 80    # Puerto dentro del contenedor al que se redirige el tráfico (debe coincidir con `containerPort` del pod).

  selector:
    service: dcsar-basic-landing-page  # Selector para asociar este Service con los pods correspondientes (basado en etiquetas).

status:
  loadBalancer: {}     # Rellenado automáticamente por Kubernetes si el tipo de Service fuera LoadBalancer (aquí queda vacío).
